ARG BASE_IMAGE

FROM ${BASE_IMAGE}

ARG GMP_TAR_XZ
ARG GMP_VERSION
ARG MPFR_TAR_XZ
ARG MPFR_VERSION
ARG MPC_TAR_GZ
ARG MPC_VERSION
ARG BINUTILS_TAR_XZ
ARG BINUTILS_VERSION

RUN microdnf install gcc g++ xz m4 diffutils \
    && microdnf clean all

RUN curl -s -L $GMP_TAR_XZ | tar xJ -C /tmp \
    && curl -s -L $MPFR_TAR_XZ | tar xJ -C /tmp \
    && curl -s -L $MPC_TAR_GZ | tar xz -C /tmp \
    && curl -s -L $BINUTILS_TAR_XZ | tar xJ -C /tmp

WORKDIR /tmp/gmp-$GMP_VERSION

RUN ./configure \
     --exec-prefix=/opt/toolchains/host \
     --prefix=/opt/toolchains/generic \
     --enable-cxx

RUN make -j 6 && make check && make install


WORKDIR /tmp/mpfr-$MPFR_VERSION

RUN ./configure \
     --with-gmp-include=/opt/toolchains/host/include/ \
     --with-gmp-lib=/opt/toolchains/host/lib/ \
     --prefix=/opt/toolchains/generic/ \
     --exec-prefix=/opt/toolchains/host/

RUN make -j 6 && make check && make install


WORKDIR /tmp/mpc-$MPC_VERSION

RUN ./configure \
     --with-gmp-include=/opt/toolchains/host/include/ \
     --with-gmp-lib=/opt/toolchains/host/lib/ \
     --with-mpfr-lib=/opt/toolchains/host/lib \
     --with-mpfr-include=/opt/toolchains/generic/include

RUN make -j 6 && make check && make install

